//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.MyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WordCount1", ReplyAction="http://tempuri.org/IService1/WordCount1Response")]
        string WordCount1(System.IO.Stream fileStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WordCount1", ReplyAction="http://tempuri.org/IService1/WordCount1Response")]
        System.Threading.Tasks.Task<string> WordCount1Async(System.IO.Stream fileStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getWsdlAddress", ReplyAction="http://tempuri.org/IService1/getWsdlAddressResponse")]
        string[] getWsdlAddress(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getWsdlAddress", ReplyAction="http://tempuri.org/IService1/getWsdlAddressResponse")]
        System.Threading.Tasks.Task<string[]> getWsdlAddressAsync(string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Number2Words", ReplyAction="http://tempuri.org/IService1/Number2WordsResponse")]
        string Number2Words(string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Number2Words", ReplyAction="http://tempuri.org/IService1/Number2WordsResponse")]
        System.Threading.Tasks.Task<string> Number2WordsAsync(string number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplication1.MyService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication1.MyService.IService1>, WebApplication1.MyService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string WordCount1(System.IO.Stream fileStream) {
            return base.Channel.WordCount1(fileStream);
        }
        
        public System.Threading.Tasks.Task<string> WordCount1Async(System.IO.Stream fileStream) {
            return base.Channel.WordCount1Async(fileStream);
        }
        
        public string[] getWsdlAddress(string url) {
            return base.Channel.getWsdlAddress(url);
        }
        
        public System.Threading.Tasks.Task<string[]> getWsdlAddressAsync(string url) {
            return base.Channel.getWsdlAddressAsync(url);
        }
        
        public string Number2Words(string number) {
            return base.Channel.Number2Words(number);
        }
        
        public System.Threading.Tasks.Task<string> Number2WordsAsync(string number) {
            return base.Channel.Number2WordsAsync(number);
        }
    }
}
